<?php
/**
 * Blog Publisher
 *
 * Handles WordPress post creation, draft management, and publishing workflow
 * for blog articles generated by the Blog Agent.
 *
 * @package MLS_Listings_Display
 * @subpackage Blog_Agent
 * @since 6.73.0
 */

if (!defined('ABSPATH')) {
    exit;
}

/**
 * Class MLD_Blog_Publisher
 *
 * WordPress post creation and publishing management.
 */
class MLD_Blog_Publisher {

    /**
     * Default post settings
     *
     * @var array
     */
    private $default_settings = array(
        'post_type' => 'post',
        'post_status' => 'draft',
        'comment_status' => 'open',
        'ping_status' => 'open',
    );

    /**
     * Image handler instance
     *
     * @var MLD_Blog_Image_Handler
     */
    private $image_handler;

    /**
     * SEO optimizer instance
     *
     * @var MLD_Blog_SEO_Optimizer
     */
    private $seo_optimizer;

    /**
     * Constructor
     */
    public function __construct() {
        // Nothing to initialize
    }

    /**
     * Set dependencies
     *
     * @param MLD_Blog_Image_Handler $image_handler
     * @param MLD_Blog_SEO_Optimizer $seo_optimizer
     */
    public function set_dependencies($image_handler, $seo_optimizer) {
        $this->image_handler = $image_handler;
        $this->seo_optimizer = $seo_optimizer;
    }

    /**
     * Create a WordPress draft from article data
     *
     * @param array $article Article data
     * @param array $options Publishing options
     * @return array Result with post ID
     */
    public function create_draft($article, $options = array()) {
        $defaults = array(
            'author_id' => get_current_user_id(),
            'category' => 'real-estate',
            'tags' => array(),
            'set_featured_image' => true,
            'add_schema' => true,
            'update_seo_plugins' => true,
        );
        $options = wp_parse_args($options, $defaults);

        // Prepare post data
        $post_data = array(
            'post_title' => wp_strip_all_tags($article['title']),
            'post_content' => $this->prepare_content($article, $options),
            'post_status' => 'draft',
            'post_type' => 'post',
            'post_author' => $options['author_id'],
            'post_excerpt' => $article['meta_description'] ?? '',
        );

        // Insert the post
        $post_id = wp_insert_post($post_data, true);

        if (is_wp_error($post_id)) {
            return array(
                'success' => false,
                'error' => $post_id->get_error_message(),
            );
        }

        // Set categories
        $this->set_categories($post_id, $options['category']);

        // Set tags
        if (!empty($options['tags'])) {
            wp_set_post_tags($post_id, $options['tags']);
        } elseif (!empty($article['meta_keywords'])) {
            $tags = array_map('trim', explode(',', $article['meta_keywords']));
            wp_set_post_tags($post_id, array_slice($tags, 0, 10));
        }

        // Set featured image
        $featured_image_id = null;
        if ($options['set_featured_image'] && !empty($article['images']['featured'])) {
            $featured_image_id = $this->set_featured_image($post_id, $article['images']['featured']);
        }

        // Update SEO plugin meta
        if ($options['update_seo_plugins']) {
            $this->update_seo_meta($post_id, $article);
        }

        // Add schema markup
        if ($options['add_schema'] && !empty($article['schema'])) {
            update_post_meta($post_id, '_mld_article_schema', $article['schema']);
        }

        // Store article metadata
        $this->store_article_metadata($post_id, $article);

        // Update blog_articles table
        $this->update_articles_table($post_id, $article);

        return array(
            'success' => true,
            'post_id' => $post_id,
            'edit_url' => get_edit_post_link($post_id, 'raw'),
            'preview_url' => get_preview_post_link($post_id),
            'featured_image_id' => $featured_image_id,
        );
    }

    /**
     * Prepare content for WordPress
     *
     * @param array $article Article data
     * @param array $options Options
     * @return string Prepared content
     */
    private function prepare_content($article, $options) {
        $content = $article['content'];

        // Ensure proper WordPress blocks format if using Gutenberg
        if ($this->is_gutenberg_active()) {
            $content = $this->convert_to_blocks($content);
        }

        // Insert content images if available
        if ($this->image_handler && !empty($article['images']['content'])) {
            $content = $this->image_handler->insert_images_in_content(
                $content,
                $article['images'],
                array('max_images' => 3)
            );
        }

        return $content;
    }

    /**
     * Check if Gutenberg is active
     *
     * @return bool
     */
    private function is_gutenberg_active() {
        return function_exists('use_block_editor_for_post_type') &&
               use_block_editor_for_post_type('post');
    }

    /**
     * Convert HTML content to Gutenberg blocks
     *
     * @param string $content HTML content
     * @return string Block content
     */
    private function convert_to_blocks($content) {
        // Wrap paragraphs in blocks
        $content = preg_replace(
            '/<p([^>]*)>(.*?)<\/p>/s',
            "<!-- wp:paragraph -->\n<p$1>$2</p>\n<!-- /wp:paragraph -->\n",
            $content
        );

        // Wrap headings in blocks
        $content = preg_replace(
            '/<h2([^>]*)>(.*?)<\/h2>/s',
            "<!-- wp:heading -->\n<h2$1>$2</h2>\n<!-- /wp:heading -->\n",
            $content
        );

        $content = preg_replace(
            '/<h3([^>]*)>(.*?)<\/h3>/s',
            "<!-- wp:heading {\"level\":3} -->\n<h3$1>$2</h3>\n<!-- /wp:heading -->\n",
            $content
        );

        // Wrap lists in blocks
        $content = preg_replace(
            '/<ul([^>]*)>(.*?)<\/ul>/s',
            "<!-- wp:list -->\n<ul$1>$2</ul>\n<!-- /wp:list -->\n",
            $content
        );

        // Wrap figures/images in blocks
        $content = preg_replace(
            '/<figure([^>]*)>(.*?)<\/figure>/s',
            "<!-- wp:image -->\n<figure$1>$2</figure>\n<!-- /wp:image -->\n",
            $content
        );

        return $content;
    }

    /**
     * Set post categories
     *
     * @param int $post_id Post ID
     * @param string|array $categories Category slugs
     */
    private function set_categories($post_id, $categories) {
        if (!is_array($categories)) {
            $categories = array($categories);
        }

        $category_ids = array();

        foreach ($categories as $cat_slug) {
            $category = get_category_by_slug($cat_slug);

            if ($category) {
                $category_ids[] = $category->term_id;
            } else {
                // Create category if it doesn't exist
                $result = wp_insert_term($cat_slug, 'category', array(
                    'slug' => sanitize_title($cat_slug),
                ));

                if (!is_wp_error($result)) {
                    $category_ids[] = $result['term_id'];
                }
            }
        }

        if (!empty($category_ids)) {
            wp_set_post_categories($post_id, $category_ids);
        }
    }

    /**
     * Set featured image for post
     *
     * @param int $post_id Post ID
     * @param array $image Image data
     * @return int|null Attachment ID or null
     */
    private function set_featured_image($post_id, $image) {
        if (!$this->image_handler) {
            return null;
        }

        $attachment_id = $this->image_handler->set_featured_image($post_id, $image);

        if (is_wp_error($attachment_id)) {
            return null;
        }

        return $attachment_id;
    }

    /**
     * Update SEO plugin meta fields
     *
     * @param int $post_id Post ID
     * @param array $article Article data
     */
    private function update_seo_meta($post_id, $article) {
        $title = $article['title'] ?? '';
        $description = $article['meta_description'] ?? '';
        $keywords = $article['meta_keywords'] ?? '';

        // Yoast SEO
        if (defined('WPSEO_VERSION')) {
            update_post_meta($post_id, '_yoast_wpseo_title', $title);
            update_post_meta($post_id, '_yoast_wpseo_metadesc', $description);
            update_post_meta($post_id, '_yoast_wpseo_focuskw', $article['primary_keyword'] ?? '');
        }

        // RankMath
        if (class_exists('RankMath')) {
            update_post_meta($post_id, 'rank_math_title', $title);
            update_post_meta($post_id, 'rank_math_description', $description);
            update_post_meta($post_id, 'rank_math_focus_keyword', $article['primary_keyword'] ?? '');
        }

        // All in One SEO
        if (class_exists('AIOSEO\Plugin\AIOSEO')) {
            update_post_meta($post_id, '_aioseo_title', $title);
            update_post_meta($post_id, '_aioseo_description', $description);
            update_post_meta($post_id, '_aioseo_keywords', $keywords);
        }
    }

    /**
     * Store article metadata for tracking
     *
     * @param int $post_id Post ID
     * @param array $article Article data
     */
    private function store_article_metadata($post_id, $article) {
        update_post_meta($post_id, '_mld_blog_agent_generated', true);
        update_post_meta($post_id, '_mld_generated_at', current_time('mysql'));
        update_post_meta($post_id, '_mld_seo_score', $article['seo_score'] ?? 0);
        update_post_meta($post_id, '_mld_geo_score', $article['geo_score'] ?? 0);
        update_post_meta($post_id, '_mld_word_count', $article['word_count'] ?? 0);
        update_post_meta($post_id, '_mld_prompt_version', $article['prompt_version'] ?? '');

        if (!empty($article['topic_id'])) {
            update_post_meta($post_id, '_mld_topic_id', $article['topic_id']);
        }

        // Store original content hash for edit distance calculation
        if (!empty($article['content'])) {
            $content_hash = hash('sha256', $article['content']);
            update_post_meta($post_id, '_mld_original_content_hash', $content_hash);
        }
    }

    /**
     * Update the blog_articles table
     *
     * @param int $post_id WordPress post ID
     * @param array $article Article data
     */
    private function update_articles_table($post_id, $article) {
        global $wpdb;

        $table = $wpdb->prefix . 'mld_blog_articles';

        $slug = sanitize_title($article['title'] ?? '');

        // Check if record exists
        $existing = $wpdb->get_var($wpdb->prepare(
            "SELECT id FROM $table WHERE wp_post_id = %d",
            $post_id
        ));

        $data = array(
            'wp_post_id' => $post_id,
            'title' => $article['title'] ?? '',
            'slug' => $slug,
            'content' => $article['content'] ?? '',
            'meta_description' => $article['meta_description'] ?? '',
            'meta_keywords' => $article['meta_keywords'] ?? '',
            'seo_score' => $article['seo_score'] ?? 0,
            'geo_score' => $article['geo_score'] ?? 0,
            'word_count' => $article['word_count'] ?? 0,
            'internal_links_count' => $this->count_internal_links($article['content'] ?? ''),
            'external_links_count' => $this->count_external_links($article['content'] ?? ''),
            'images_count' => $this->count_images($article['content'] ?? ''),
            'cta_type' => $article['cta_type'] ?? '',
            'cta_position' => $article['cta_position'] ?? '',
            'schema_markup' => !empty($article['schema']) ? wp_json_encode($article['schema']) : null,
            'prompt_version' => $article['prompt_version'] ?? '',
            'status' => 'draft',
            'original_content_hash' => hash('sha256', $article['content'] ?? ''),
        );

        if (!empty($article['topic_id'])) {
            $data['topic_id'] = $article['topic_id'];
        }

        if (!empty($article['stats'])) {
            $data['generation_tokens'] = $article['stats']['tokens_used'] ?? 0;
            $data['generation_cost'] = $article['stats']['cost'] ?? 0;
            $data['ai_provider'] = $article['stats']['provider'] ?? '';
            $data['ai_model'] = $article['stats']['model'] ?? '';
        }

        if ($existing) {
            $wpdb->update($table, $data, array('id' => $existing));
        } else {
            $wpdb->insert($table, $data);
        }
    }

    /**
     * Count internal links in content
     *
     * @param string $content HTML content
     * @return int Count
     */
    private function count_internal_links($content) {
        preg_match_all('/<a[^>]+href=["\']([^"\']*bmnboston\.com[^"\']*|\/[^"\']*)["\'][^>]*>/i', $content, $matches);
        return count($matches[0]);
    }

    /**
     * Count external links in content
     *
     * @param string $content HTML content
     * @return int Count
     */
    private function count_external_links($content) {
        preg_match_all('/<a[^>]+href=["\']https?:\/\/(?!bmnboston\.com)[^"\']+["\'][^>]*>/i', $content, $matches);
        return count($matches[0]);
    }

    /**
     * Count images in content
     *
     * @param string $content HTML content
     * @return int Count
     */
    private function count_images($content) {
        preg_match_all('/<img[^>]+>/i', $content, $matches);
        return count($matches[0]);
    }

    /**
     * Publish a draft post
     *
     * @param int $post_id Post ID
     * @param array $options Publishing options
     * @return array Result
     */
    public function publish($post_id, $options = array()) {
        $defaults = array(
            'schedule_date' => null,
            'record_feedback' => true,
        );
        $options = wp_parse_args($options, $defaults);

        $post = get_post($post_id);

        if (!$post) {
            return array(
                'success' => false,
                'error' => 'Post not found',
            );
        }

        // Record edit distance before publishing
        if ($options['record_feedback']) {
            $this->record_edit_distance($post_id, $post->post_content);
        }

        // Prepare update data
        $update_data = array(
            'ID' => $post_id,
            'post_status' => 'publish',
        );

        // Handle scheduled publishing
        if (!empty($options['schedule_date'])) {
            $update_data['post_status'] = 'future';
            $update_data['post_date'] = $options['schedule_date'];
            $update_data['post_date_gmt'] = get_gmt_from_date($options['schedule_date']);
        }

        $result = wp_update_post($update_data, true);

        if (is_wp_error($result)) {
            return array(
                'success' => false,
                'error' => $result->get_error_message(),
            );
        }

        // Update articles table
        global $wpdb;
        $table = $wpdb->prefix . 'mld_blog_articles';
        $wpdb->update(
            $table,
            array(
                'status' => 'published',
                'published_at' => current_time('mysql'),
                'published_content_hash' => hash('sha256', $post->post_content),
            ),
            array('wp_post_id' => $post_id)
        );

        // Update topic status
        $topic_id = get_post_meta($post_id, '_mld_topic_id', true);
        if ($topic_id) {
            $topics_table = $wpdb->prefix . 'mld_blog_topics';
            $wpdb->update(
                $topics_table,
                array('status' => 'published'),
                array('id' => $topic_id)
            );
        }

        return array(
            'success' => true,
            'post_id' => $post_id,
            'url' => get_permalink($post_id),
            'status' => $update_data['post_status'],
        );
    }

    /**
     * Record edit distance for learning
     *
     * @param int $post_id Post ID
     * @param string $current_content Current post content
     */
    private function record_edit_distance($post_id, $current_content) {
        $original_hash = get_post_meta($post_id, '_mld_original_content_hash', true);

        if (empty($original_hash)) {
            return;
        }

        global $wpdb;

        // Get original content from articles table
        $table = $wpdb->prefix . 'mld_blog_articles';
        $article = $wpdb->get_row($wpdb->prepare(
            "SELECT id, content FROM $table WHERE wp_post_id = %d",
            $post_id
        ), ARRAY_A);

        if (!$article) {
            return;
        }

        // Calculate edit distance (Levenshtein)
        $original_plain = strip_tags($article['content']);
        $current_plain = strip_tags($current_content);

        // Use similar_text for percentage (Levenshtein can be too expensive for long strings)
        similar_text($original_plain, $current_plain, $similarity);
        $edit_distance = 100 - $similarity; // Higher = more edited

        // Update articles table
        $wpdb->update(
            $table,
            array('edit_distance' => round($edit_distance)),
            array('id' => $article['id'])
        );

        // Record in feedback table
        $feedback_table = $wpdb->prefix . 'mld_blog_feedback';
        $wpdb->insert($feedback_table, array(
            'article_id' => $article['id'],
            'feedback_type' => 'edit_distance',
            'metric_name' => 'content_similarity',
            'metric_value' => $similarity,
            'metadata' => wp_json_encode(array(
                'original_length' => strlen($original_plain),
                'final_length' => strlen($current_plain),
                'edit_percentage' => $edit_distance,
            )),
        ));
    }

    /**
     * Record user rating
     *
     * @param int $post_id Post ID
     * @param int $rating Rating 1-5
     * @return bool Success
     */
    public function record_rating($post_id, $rating) {
        $rating = max(1, min(5, intval($rating)));

        global $wpdb;

        $table = $wpdb->prefix . 'mld_blog_articles';
        $article_id = $wpdb->get_var($wpdb->prepare(
            "SELECT id FROM $table WHERE wp_post_id = %d",
            $post_id
        ));

        if (!$article_id) {
            return false;
        }

        // Update article rating
        $wpdb->update(
            $table,
            array('user_rating' => $rating),
            array('id' => $article_id)
        );

        // Record in feedback table
        $feedback_table = $wpdb->prefix . 'mld_blog_feedback';
        $wpdb->insert($feedback_table, array(
            'article_id' => $article_id,
            'feedback_type' => 'user_rating',
            'metric_name' => 'content_rating',
            'metric_value' => $rating,
        ));

        return true;
    }

    /**
     * Get post by article ID
     *
     * @param int $article_id Blog agent article ID
     * @return WP_Post|null WordPress post
     */
    public function get_post_by_article_id($article_id) {
        global $wpdb;

        $table = $wpdb->prefix . 'mld_blog_articles';
        $post_id = $wpdb->get_var($wpdb->prepare(
            "SELECT wp_post_id FROM $table WHERE id = %d",
            $article_id
        ));

        if (!$post_id) {
            return null;
        }

        return get_post($post_id);
    }

    /**
     * Get recent generated articles
     *
     * @param int $limit Number of articles
     * @return array Articles
     */
    public function get_recent_articles($limit = 10) {
        global $wpdb;

        $table = $wpdb->prefix . 'mld_blog_articles';

        return $wpdb->get_results($wpdb->prepare(
            "SELECT a.*, p.post_title, p.post_status, p.post_date
             FROM $table a
             LEFT JOIN {$wpdb->posts} p ON a.wp_post_id = p.ID
             ORDER BY a.created_at DESC
             LIMIT %d",
            $limit
        ), ARRAY_A);
    }
}
