<?php
/**
 * ID Generator class
 *
 * @package Exclusive_Listings
 * @since 1.0.0
 */

// Prevent direct access
if (!defined('ABSPATH')) {
    exit;
}

/**
 * Class EL_ID_Generator
 *
 * Generates unique sequential IDs for exclusive listings.
 * Uses MySQL auto-increment to ensure thread-safety and uniqueness.
 *
 * ID Strategy:
 * - Exclusive listings: IDs starting from 1, incrementing sequentially
 * - MLS listings: IDs in the 60,000,000+ range (Bridge MLS assigned)
 * - Detection: listing_id < 1,000,000 = exclusive listing
 */
class EL_ID_Generator {

    /**
     * WordPress database object
     * @var wpdb
     */
    private $wpdb;

    /**
     * Sequence table name
     * @var string
     */
    private $table;

    /**
     * Constructor
     */
    public function __construct() {
        global $wpdb;
        $this->wpdb = $wpdb;
        $this->table = $wpdb->prefix . 'exclusive_listing_sequence';
    }

    /**
     * Generate a new unique listing ID
     *
     * Uses MySQL auto-increment to guarantee uniqueness even under
     * concurrent requests from multiple agents.
     *
     * @since 1.0.0
     * @return int|WP_Error New listing ID or WP_Error on failure
     */
    public function generate() {
        // Insert a new row to get the next auto-increment ID
        $result = $this->wpdb->query("INSERT INTO {$this->table} VALUES (NULL)");

        if ($result === false) {
            error_log('Exclusive Listings: Failed to generate ID - ' . $this->wpdb->last_error);
            return new WP_Error(
                'id_generation_failed',
                'Failed to generate a new listing ID',
                array('db_error' => $this->wpdb->last_error)
            );
        }

        $new_id = $this->wpdb->insert_id;

        if (!$new_id) {
            error_log('Exclusive Listings: Generated ID is 0 or null');
            return new WP_Error(
                'id_generation_failed',
                'Generated ID is invalid'
            );
        }

        // Log the generation for debugging
        if (defined('WP_DEBUG') && WP_DEBUG) {
            error_log("Exclusive Listings: Generated new ID {$new_id}");
        }

        return (int) $new_id;
    }

    /**
     * Generate a listing_key hash for the given listing ID
     *
     * The listing_key is used for API deduplication and is stored
     * alongside the listing_id in BME tables.
     *
     * @since 1.0.0
     * @param int $listing_id The listing ID
     * @param int|null $agent_id Optional agent/user ID
     * @return string MD5 hash listing_key
     */
    public function generate_listing_key($listing_id, $agent_id = null) {
        $timestamp = current_time('mysql');
        $user_id = $agent_id ?: get_current_user_id();

        // Create a unique hash from listing ID, timestamp, and agent
        $key_string = sprintf(
            'exclusive_%d_%s_%d_%s',
            $listing_id,
            $timestamp,
            $user_id,
            wp_generate_password(8, false) // Add randomness
        );

        return md5($key_string);
    }

    /**
     * Get the next ID that will be assigned (without consuming it)
     *
     * @since 1.0.0
     * @return int Next available ID
     */
    public function peek_next_id() {
        // Get the current auto_increment value
        $result = $this->wpdb->get_row(
            $this->wpdb->prepare(
                "SHOW TABLE STATUS LIKE %s",
                $this->table
            )
        );

        if ($result && isset($result->Auto_increment)) {
            return (int) $result->Auto_increment;
        }

        // Fallback: get max ID + 1
        $max_id = $this->wpdb->get_var("SELECT MAX(id) FROM {$this->table}");
        return $max_id ? (int) $max_id + 1 : 1;
    }

    /**
     * Get the last generated ID
     *
     * @since 1.0.0
     * @return int|null Last generated ID or null if none exist
     */
    public function get_last_id() {
        $last_id = $this->wpdb->get_var("SELECT MAX(id) FROM {$this->table}");
        return $last_id ? (int) $last_id : null;
    }

    /**
     * Get the count of generated IDs
     *
     * @since 1.0.0
     * @return int Number of IDs generated
     */
    public function get_count() {
        return (int) $this->wpdb->get_var("SELECT COUNT(*) FROM {$this->table}");
    }

    /**
     * Check if an ID is an exclusive listing ID
     *
     * @since 1.0.0
     * @param int $listing_id The listing ID to check
     * @return bool True if exclusive, false if MLS
     */
    public static function is_exclusive($listing_id) {
        return $listing_id < EL_EXCLUSIVE_ID_THRESHOLD;
    }

    /**
     * Check if an ID was generated by this plugin
     *
     * @since 1.0.0
     * @param int $listing_id The listing ID to check
     * @return bool True if the ID exists in our sequence table
     */
    public function is_our_id($listing_id) {
        $exists = $this->wpdb->get_var(
            $this->wpdb->prepare(
                "SELECT id FROM {$this->table} WHERE id = %d",
                $listing_id
            )
        );

        return (bool) $exists;
    }

    /**
     * Reserve a specific ID (for data migration purposes)
     *
     * WARNING: This should only be used for data migration or recovery.
     * Normal operation should always use generate() to get the next ID.
     *
     * @since 1.0.0
     * @param int $id The ID to reserve
     * @return bool True on success, false on failure
     */
    public function reserve_id($id) {
        if ($this->is_our_id($id)) {
            return true;
        }

        $result = $this->wpdb->insert($this->table, array('id' => $id), array('%d'));

        if ($result === false) {
            error_log("Exclusive Listings: Failed to reserve ID {$id}");
            return false;
        }

        return true;
    }

    /**
     * Get diagnostic information about the ID generator
     *
     * @since 1.0.0
     * @return array Diagnostic data
     */
    public function get_diagnostics() {
        return array(
            'table' => $this->table,
            'table_exists' => $this->table_exists(),
            'last_id' => $this->get_last_id(),
            'next_id' => $this->peek_next_id(),
            'total_generated' => $this->get_count(),
            'threshold' => EL_EXCLUSIVE_ID_THRESHOLD,
        );
    }

    /**
     * Check if the sequence table exists
     *
     * @since 1.0.0
     * @return bool True if table exists
     */
    private function table_exists() {
        $exists = $this->wpdb->get_var(
            $this->wpdb->prepare(
                "SHOW TABLES LIKE %s",
                $this->table
            )
        );

        return (bool) $exists;
    }
}
